### ISSUE TITLE
Baking out data

### ISSUE THREAD

**Issue by ItsRogueRen** [radiatoryang/lipstick#1]
According to the listed licensing, if I bake out the data from this repo, I own that data. So in theory could I then add that data back into a Unity project and release the whole project as open-source, lipsync data included?

**Comment by radiatoryang** [comment]
Hello. Your reading is correct, I think, but again I'm not a lawyer and can't say if Oculus-Facebook won't ever come after you

But more importantly, uhhh this repo doesn't actually do anything yet, this is literally just the Oculus lipsync package imported into Unity, I never had time to actually complete any of my roadmap or plans, sorry
